import type { Metadata } from "next";
import "@/app/globals.css";
import Header from "@/components/header/Index";
import Footer from "@/components/footer/Index";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased w-full`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
